require "~/dev/sonic-pi-projects/serialisms/modules/generate_fibonacci_matrix.rb"
require "~/dev/sonic-pi-projects/serialisms/modules/generate_fibonacci_sequence.rb"
require "~/dev/sonic-pi-projects/serialisms/modules/generate_overtone_matrix.rb"
require "~/dev/sonic-pi-projects/serialisms/modules/generate_serial_matrix.rb"
require "~/dev/sonic-pi-projects/serialisms/modules/midi_to_freq.rb"
require "~/dev/sonic-pi-projects/serialisms/modules/midi_to_freq.rb"